// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
)

func main() {
	resp, err := http.Get("https://d201a2mn26r7lk.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	content, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	resp.Body.Close()

	f, err := os.Create("builtin_source.go")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	f.WriteString("package schema\n\n")
	f.WriteString("// Generated by generate_builtin.go. DO NOT EDIT.\n\n")
	fmt.Fprintf(f, "const builtinSource = %q\n", content)
}
